export interface TransactionFormData {
    animal_id?: string;
    transaction_type: string;
    transaction_status: string;
    price: number;
    tax_amount: number;
    currency: string;
    transaction_date: string;
    delivery_date?: string | null;
    details?: string | null;
    payment_method: string;
    payment_reference?: string | null;
    deposit_amount?: number | null;
    payment_due_date?: string | null;
    seller_id?: number;
    buyer_id?: number;
    seller_name: string;
    seller_company?: string | null;
    seller_tax_id?: string | null;
    seller_email?: string | null;
    seller_phone?: string | null;
    seller_address?: string | null;
    seller_city?: string | null;
    seller_state?: string | null;
    seller_country?: string | null;
    seller_postal_code?: string | null;
    seller_identification?: string | null;
    seller_license_number?: string | null;
    buyer_name: string;
    buyer_company?: string | null;
    buyer_tax_id?: string | null;
    buyer_email?: string | null;
    buyer_phone?: string | null;
    buyer_address?: string | null;
    buyer_city?: string | null;
    buyer_state?: string | null;
    buyer_country?: string | null;
    buyer_postal_code?: string | null;
    buyer_identification?: string | null;
    buyer_license_number?: string | null;
    invoice_number?: string | null;
    contract_number?: string | null;
    terms_accepted?: boolean | null;
    health_certificate_number?: string | null;
    transport_license_number?: string | null;
    location_of_sale?: string | null;
    terms_and_conditions?: string | null;
    special_conditions?: string | null;
    delivery_instructions?: string | null;
    insurance_policy_number?: string | null;
    insurance_amount?: number | null;
  }
  